const GET_ALL_DOGS = "GET_ALL_DOGS"
const GET_DOGS_ID = "GET_DOGS_ID"
const GET_DOGS_NAME = "GET_DOGS_NAME"
const GET_TEMPERAMENTS = "GET_TEMPERAMENTS"
const ADD_DOG = "ADD_DOG"
const CLEAR_DATA = "CLEAR_DATA"
const FILTER = "FILTER"
const PAGINATE = "PAGINATE"
const ORDER_BY_NAME = "ORDER_BY_NAME"
const ORDER_BY_WEIGHT = "ORDER_BY_WEIGHT"
const FILTER_BY_DB = "FILTER_BY_DB"
const FILTER_BY_TEMPER = "FILTER_BY_TEMPER"

module.exports = {
    GET_ALL_DOGS,
    GET_DOGS_ID,
    GET_TEMPERAMENTS,
    ADD_DOG,
    GET_DOGS_NAME,
    CLEAR_DATA,
    FILTER,
    PAGINATE,
    ORDER_BY_NAME,
    ORDER_BY_WEIGHT,
    FILTER_BY_DB,
    FILTER_BY_TEMPER
}